### ISSUE TITLE
Throws an error if client scope is not enabled

### ISSUE THREAD

**Issue by andcam** [RickGroenewegen/bugsnag-coldfusion#1]
Railo 4.1.2.005 Error (expression)
Message client scope is not enabled
Detail  you can enable client scope with tag cfapplication/Application.cfc
Stacktrace  The Error Occurred in
/XXXX/BugSnag.cfc: line 108 
106: "request" : #serializeScope(scope = request)#, 
107: "session" : #serializeScope(scope = session)#, 
108: "client" : #serializeScope(scope = client)#, 
109: "CGI" : #serializeScope(scope = cgi)#,
110: "cookie" : #serializeScope(scope = cookie)#

**Comment by RickGroenewegen** [comment]
Ah you're right. I've implemented a check to detect if the application, session and / or cookie scopes are enabled.

**Comment by andcam** [comment]
@RickGroenewegen thanks!
